export const DEFAULT_BOT_NAMES = [
  "nightbot",
  "streamelements",
  "wizebot",
  "moobot",
  "streamlabs",
  "commanderroot",
  "sery_bot",
  "fossabot",
  "buttsbot",
  "xanbot",
  "vivbot",
  "botisimo",
  "potatbotat",
  "supibot",
  "coebot",
  "spanixbot",
  "ohbot",
  "twirapp",
  "susgeebot",
  "oshbt",
  "rvbies",
  "deepbot",
  "ankhbot",
  "phantombot",
  "pajbot",
  "scriptorex",
  "gempbot",
  "turtegbot",
  "streamqbot",
] as const;

export const DEFAULT_KICK_BOT_NAMES = [
  "twirbot",
  "fossabot",
  "botrix",
  "kickbot",
] as const;
